#!/usr/bin/env bash
[[ -f .env ]] && source .env

ENVRIONMENT=$1
ROLE=$2
NODEOS_ARGS=$3
INIT_MODE=$4
INIT_DATA=$5
EOSIO_VERSION=${6:-latest}
EOSIO_IMAGE=${7:-waxtools/nodeos} # Imported from .env
NODEOS_DATA_ROOT=${8:-$NODEOS_DATA_ROOT} # Imported from .env
NODEOS_CONFIG_ROOT=${9:-$NODEOS_CONFIG_ROOT} # Imported from .env

NODEOS_USERNAME=wax${ENVRIONMENT}
NODEOS_USERID=$(id -u "$NODEOS_USERNAME")
NODEOS_GROUPID=$(getent group $OS_GROUP_EOSIO | cut -d: -f3)

make up-$ENVRIONMENT-$ROLE \
EOSIO_VERSION=$EOSIO_VERSION \
NODEOS_USER="$NODEOS_USERID" \
NODEOS_GROUP="$NODEOS_GROUPID" \
NODEOS_ARGS=$NODEOS_ARGS \
INIT_MODE="$INIT_MODE" \
INIT_DATA="$INIT_DATA" \
EOSIO_IMAGE=$EOSIO_IMAGE \
CONFIG_ROOT_PATH=$NODEOS_CONFIG_ROOT \
DATA_ROOT_PATH="$NODEOS_DATA_ROOT"
