version: "3"

services:
  nodeos:
    image: ${EOSIO_IMAGE}
    build:
      context: ../images/nodeos
    #user: ${NODEOS_USER}:${NODEOS_GROUP}
    command: ["--data-dir /eos-data --config-dir /eos-config --logconf /eos-config/logging.json ${NODEOS_ARGS}", "${INIT_MODE}", "${INIT_DATA}"]
    container_name: ${NODEOS_CONTAINER_NAME}
    volumes:
      - ${NODEOS_CONFIG_PATH}:/eos-config
      - ${NODEOS_DATA_PATH}:/eos-data
      - ${NODEOS_SHARED_PATH}:/eos-shared
